### ISSUE TITLE
Kyo 320

### ISSUE THREAD

**Issue by TheJim0** [lorenzo-deluca/espkyogate#42]
Buondì,questa integrazione può funzionare anche con la kyo320?

**Comment by TheJim0** [comment]
Ho provato a caricare il file yaml solo con gli eventi di sistema senza le zone e mi appare questo messaggio nei log
![image](https://github.com/lorenzo-deluca/espkyogate/assets/136650000/5d00231c-2c12-4af1-9055-512b7543fa2f)

**Comment by lorenzo-deluca** [comment]
Ciao, è da testare ;)
Allora, dall'errore sembra che non risponda proprio nulla, hai già provato a invertire TX e RX?
Non sei in programmazione della centrale giusto?

Poi, per un log della porta seriale più dettagliato dovresti abilitare il logging seriale:

```yaml
service: esphome.espkyogate_debug_command
data:
  serial_trace: 1
  log_trace: 1
  polling_kyo: 1
```
