### ISSUE TITLE
servizio Reset Alarm Memory

### ISSUE THREAD

**Issue by popeye70** [lorenzo-deluca/espkyogate#59]
Ciao Lorenzo,
gentilmente mi confermi la sintassi da utilizzare per chiamare il servizio:
_service: esphome.espkyogate_reset_alarms_
affinchè cancelli gli errori in memoria di tutte le zone (io ne ho cinque) esistenti?

Al momento ho pedestremente copiato quanto indicato nel manuale:
_service: esphome.espkyogate_reset_alarms
data: {}_
ma sembrerebbe non funzionare...

Grazie mille
Flavio

**Comment by serucci** [comment]
Ciao, confermo la sintassi corretta
```
alias: Reset Memoria Allarme
sequence:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: esphome.espkyogatebox_reset_alarms
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: notify.xxxx
    data:
      message: "Inviato comando reset memorie allarmi "
mode: single
```
