### ISSUE TITLE
ESPHome 2025.2.0 e Custom Components

### ISSUE THREAD

**Issue by gianlucaf81** [lorenzo-deluca/espkyogate#63]
So che l'aggiornamento è di ieri, ma volevo sapere se la questione verrà affrontata.
Grazie.

`INFO ESPHome 2025.2.0
INFO Reading configuration /root/config/bentel-kyo4.yaml...
Failed config

binary_sensor.custom: [source /root/config/bentel-kyo4.yaml:52]
  
  The "custom" component has been removed. Consider conversion to an external component.
  https://esphome.io/guides/contributing#a-note-about-custom-components.
  platform: custom
  lambda: |-
    auto kyo32 = new Bentel_Kyo32(id(uart_bus));
    App.register_component(kyo32);
    return {
      kyo32->kyo_comunication,
      kyo32->stato_sirena,
      kyo32->warn_mancanza_rete,
      kyo32->sabotaggio_zona, 
      kyo32->sabotaggio_sistema,
      kyo32->warn_scomparsa_bpi,`

**Comment by cannos88** [comment]
io ci sto lavorando, appena ho la soluzione definitiva farò una pull request, in ogni caso si tratterebbe solo di modificare il file yaml e al massimo aggiungere un secondo file esterno insieme al .h già presente

**Comment by lorenzo-deluca** [comment]
Grande @cannos88, ottimo! 👍 

Tra l'altro sarebbe anche comodo far puntare lo YAML al file .h nel direttamente dal repository GitHub, così ogni volta vi trovate la nuova versione.

**Comment by adepiero** [comment]
@cannos88, oltre alla parte della platform, c'è da sistemare anche la parte iniziale dello YAML, sempre per sintassi deprecate. Sistemi tu, per favore? La nuova sintassi, almeno per le board ESP32 come la mia, è:

```
esphome:
  name: espkyogate
  friendly_name: Allarme
  comment: Alarm System Serial to HA controller
  includes:
    - components/bentel-kyo/bentel_kyo32.h

esp32:
  board: esp32doit-devkit-v1
```
